name: swifty_chat_data
description: Data package for the swifty_chat package.
version: 0.1.1
repository: https://github.com/EnesKaraosman/swifty_chat_data

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  # https://pub.dev/packages/equatable
  equatable: ^2.0.5

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter